apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "postgres.fullname" . }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres.labels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          ports:
            - name: tcp-postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.existingSecret }}
                  key: {{ .Values.auth.secretKeys.password }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            {{- if .Values.config.maxConnections }}
            - name: POSTGRES_INITDB_ARGS
              value: "--auth-host=scram-sha-256"
            {{- end }}
          args:
            {{- if .Values.config.maxConnections }}
            - "-c"
            - "max_connections={{ .Values.config.maxConnections }}"
            {{- end }}
            {{- if .Values.config.sharedBuffers }}
            - "-c"
            - "shared_buffers={{ .Values.config.sharedBuffers }}"
            {{- end }}
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.auth.username | quote }}
                - -d
                - {{ .Values.auth.database | quote }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.auth.username | quote }}
                - -d
                - {{ .Values.auth.database | quote }}
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.storage.storageClass }}
        storageClassName: {{ .Values.storage.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
