/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    versions: Version;
    contributors: Contributor;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    services: {
      versions: 'versions';
      'settings.contributors': 'contributors';
    };
  };
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    versions: VersionsSelect<false> | VersionsSelect<true>;
    contributors: ContributorsSelect<false> | ContributorsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr') | ('en' | 'fr')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'fr';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  name: string;
  slug?: string | null;
  /**
   * This field is not visible to end users.
   */
  description?: string | null;
  organizationId?: string | null;
  supportingOrganizationIds?: string[] | null;
  publishedVersion?: (string | null) | Version;
  versions?: {
    docs?: (string | Version)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  settings?: {
    contributors?: {
      docs?: (string | Contributor)[];
      hasNextPage?: boolean;
      totalDocs?: number;
    };
    /**
     * Add Consent Documents by ID. Visit the Consent Manager to identify the Consent Document.
     */
    consent?:
      | {
          documentId: string;
          id?: string | null;
        }[]
      | null;
    delegate?: {
      /**
       * When enabled, applicants can authorize a delegate to help manage this service.
       */
      access?: boolean | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "versions".
 */
export interface Version {
  id: string;
  categories?:
    | (
        | 'culture'
        | 'education'
        | 'employment'
        | 'family'
        | 'financial'
        | 'health'
        | 'housing'
        | 'legal'
        | 'personal'
        | 'social'
      )[]
    | null;
  description?: {
    short?: string | null;
    long?: string | null;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Connect an application to this service.
   */
  application?: {
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    applications?:
      | (
          | {
              /**
               * If applicable, add a downloadable application.
               */
              online?:
                | {
                    label?: string | null;
                    description?: string | null;
                    apiKey?: string | null;
                    formId?: string | null;
                    url?: string | null;
                    id?: string | null;
                  }[]
                | null;
              /**
               * If applicable, add a downloadable application.
               */
              download?:
                | {
                    label?: string | null;
                    description?: string | null;
                    url?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'form';
            }
          | {
              label?: string | null;
              description?: string | null;
              url?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'link';
            }
          | {
              label?: string | null;
              description?: string | null;
              method?: ('GET' | 'POST') | null;
              url?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'workflow';
            }
        )[]
      | null;
  };
  products?:
    | {
        label: string;
        description?: string | null;
        /**
         * Price in dollars (e.g. 25.00)
         */
        price: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Add an estimated processing time so applicants have an idea of how long they must wait from application to service delivery.
   */
  processingTime?: {
    values?: {
      min?: {
        value?: number | null;
        unit?: ('minutes' | 'hours' | 'days' | 'weeks' | 'months' | 'years') | null;
      };
      max?: {
        value?: number | null;
        unit?: ('minutes' | 'hours' | 'days' | 'weeks' | 'months' | 'years') | null;
      };
    };
  };
  /**
   * Details you provide here will help users find your service.
   */
  eligibilityCriteria?: {
    /**
     * If the service has any age requirements, add them below.
     */
    age?: {
      description?: string | null;
      values?: {
        min?: number | null;
        max?: number | null;
      };
    };
    /**
     * If the service has any employment requirements, add them below.
     */
    employment?: {
      description?: string | null;
      /**
       * Select all values which apply to this service.
       */
      values?: ('employed-full-time' | 'employed-part-time' | 'self-employed' | 'unemployed')[] | null;
    };
    /**
     * If the service has any shelter requirements, add them below.
     */
    housing?: {
      description?: string | null;
      /**
       * Select all values which apply to this service.
       */
      values?: ('home-owner' | 'renter' | 'subsidized-housing' | 'temporary-accommodation' | 'unhoused')[] | null;
    };
    /**
     * If the service has any income level requirements, add them below.
     */
    income?: {
      description?: string | null;
      household?: {
        min?: number | null;
        max?: number | null;
      };
      personal?: {
        min?: number | null;
        max?: number | null;
      };
    };
    /**
     * If the service has any relationship requirements, add them below
     */
    relationship?: {
      description?: string | null;
      /**
       * Select all values which apply to this service.
       */
      values?: ('married' | 'common-law' | 'separated' | 'divorced' | 'single')[] | null;
    };
    /**
     * If the service has any residency requirements, add them below.
     */
    residency?: {
      description?: string | null;
      /**
       * Select all values which apply to this service.
       */
      values?: ('citizen' | 'permanent-resident' | 'work-permit' | 'student-permit' | 'temporary-resident')[] | null;
    };
  };
  /**
   * Provide quick solutions to commonly asked questions.
   */
  faq?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add resources which can provide more detailed information about the service.
   */
  resources?: {
    applicationSupport?:
      | {
          label: string;
          description?: string | null;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Add contact methods for users to communicate about the service.
     */
    contactMethods?: {
      address?:
        | {
            label: string;
            description?: string | null;
            addressOne: string;
            addressTwo?: string | null;
            city: string;
            province: string;
            country: string;
            id?: string | null;
          }[]
        | null;
      email?:
        | {
            label: string;
            description?: string | null;
            value: string;
            id?: string | null;
          }[]
        | null;
      fax?:
        | {
            label: string;
            description?: string | null;
            value: string;
            id?: string | null;
          }[]
        | null;
      phone?:
        | {
            label: string;
            description?: string | null;
            value: string;
            id?: string | null;
          }[]
        | null;
      web?:
        | {
            label: string;
            description?: string | null;
            value: string;
            id?: string | null;
          }[]
        | null;
    };
    legal?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    otherServices?: {
      recommendedServices?: (string | Service)[] | null;
      relatedServices?: (string | Service)[] | null;
    };
    recommendedReading?:
      | {
          label?: string | null;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  publishedAt?: string | null;
  archivedAt?: string | null;
  service: string | Service;
  status?: ('draft' | 'published' | 'archived') | null;
  version?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contributors".
 */
export interface Contributor {
  id: string;
  service: string | Service;
  user: string | User;
  role: 'owner' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'user';
  fullName?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'versions';
        value: string | Version;
      } | null)
    | ({
        relationTo: 'contributors';
        value: string | Contributor;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  organizationId?: T;
  supportingOrganizationIds?: T;
  publishedVersion?: T;
  versions?: T;
  settings?:
    | T
    | {
        contributors?: T;
        consent?:
          | T
          | {
              documentId?: T;
              id?: T;
            };
        delegate?:
          | T
          | {
              access?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "versions_select".
 */
export interface VersionsSelect<T extends boolean = true> {
  categories?: T;
  description?:
    | T
    | {
        short?: T;
        long?: T;
      };
  content?: T;
  application?:
    | T
    | {
        description?: T;
        applications?:
          | T
          | {
              form?:
                | T
                | {
                    online?:
                      | T
                      | {
                          label?: T;
                          description?: T;
                          apiKey?: T;
                          formId?: T;
                          url?: T;
                          id?: T;
                        };
                    download?:
                      | T
                      | {
                          label?: T;
                          description?: T;
                          url?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              link?:
                | T
                | {
                    label?: T;
                    description?: T;
                    url?: T;
                    id?: T;
                    blockName?: T;
                  };
              workflow?:
                | T
                | {
                    label?: T;
                    description?: T;
                    method?: T;
                    url?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  products?:
    | T
    | {
        label?: T;
        description?: T;
        price?: T;
        id?: T;
      };
  processingTime?:
    | T
    | {
        values?:
          | T
          | {
              min?:
                | T
                | {
                    value?: T;
                    unit?: T;
                  };
              max?:
                | T
                | {
                    value?: T;
                    unit?: T;
                  };
            };
      };
  eligibilityCriteria?:
    | T
    | {
        age?:
          | T
          | {
              description?: T;
              values?:
                | T
                | {
                    min?: T;
                    max?: T;
                  };
            };
        employment?:
          | T
          | {
              description?: T;
              values?: T;
            };
        housing?:
          | T
          | {
              description?: T;
              values?: T;
            };
        income?:
          | T
          | {
              description?: T;
              household?:
                | T
                | {
                    min?: T;
                    max?: T;
                  };
              personal?:
                | T
                | {
                    min?: T;
                    max?: T;
                  };
            };
        relationship?:
          | T
          | {
              description?: T;
              values?: T;
            };
        residency?:
          | T
          | {
              description?: T;
              values?: T;
            };
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  resources?:
    | T
    | {
        applicationSupport?:
          | T
          | {
              label?: T;
              description?: T;
              value?: T;
              id?: T;
            };
        contactMethods?:
          | T
          | {
              address?:
                | T
                | {
                    label?: T;
                    description?: T;
                    addressOne?: T;
                    addressTwo?: T;
                    city?: T;
                    province?: T;
                    country?: T;
                    id?: T;
                  };
              email?:
                | T
                | {
                    label?: T;
                    description?: T;
                    value?: T;
                    id?: T;
                  };
              fax?:
                | T
                | {
                    label?: T;
                    description?: T;
                    value?: T;
                    id?: T;
                  };
              phone?:
                | T
                | {
                    label?: T;
                    description?: T;
                    value?: T;
                    id?: T;
                  };
              web?:
                | T
                | {
                    label?: T;
                    description?: T;
                    value?: T;
                    id?: T;
                  };
            };
        legal?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        otherServices?:
          | T
          | {
              recommendedServices?: T;
              relatedServices?: T;
            };
        recommendedReading?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  publishedAt?: T;
  archivedAt?: T;
  service?: T;
  status?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contributors_select".
 */
export interface ContributorsSelect<T extends boolean = true> {
  service?: T;
  user?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  id?: T;
  role?: T;
  fullName?: T;
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}